#!/usr/bin/env perl
use lib 'lib';
use Mojolicious::Lite;
use Diary;

helper index_years => sub {
    my $c = shift;
    Diary::years;
};

helper entries_for_year => sub {
    my $c = shift;
    Diary::entries(@_);
};

get '/' => sub {
  my $c = shift;
  $c->stash(year => undef);
  $c->render('index');
} => 'index';

get '/:year' => [year => qr/\d{4}/] => sub {
  my $c = shift;
  $c->render('diary');
} => 'diary';

app->start;
